spring:
  profiles.active: development
  application:
      name: customer-service
  jackson:
      serialization:
          indent_output: true

---
spring:
    profiles: production
    data:
        mongodb:
            host: mongoinit.springboot.svc.cluster.local
            port: 27017
server:
    port: 8080

---
spring:
    profiles: development
    data:
        mongodb:
          host: 127.0.0.1
          port: 27017
server:
    port: 5000
