
spring:
    application:
        name: customer-service
    data:
        mongodb:
            host: mongoinit.springboot.svc.cluster.local
            port: 27017
    jackson:
        serialization:
            indent_output: true
server:
    port: 8080
