# TODO workout how to externalise properties
spring:
    application:
        name: customer-service
    data:
        mongodb:
            # host: mongoinit.springboot.svc.cluster.local
            host: 72.17.0.2
            port: 27017
    jackson:
        serialization:
            indent_output: true
server:
    port: 8080